name: UpdateCSV

on:
  push:
    branches: [cachehack]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout emergenzeHack/covid19italia
      uses: actions/checkout@v2
      with:
        repository: emergenzeHack/covid19italia
        ref: lang_gr

    - name: Get data repository name
      run: |
        echo "::set-output name=repo::${GITHUB_REPOSITORY%_*}_data"
      id: get_data_repo

    - name: Checkout ${{steps.get_data_repo.outputs.repo }}
      uses: actions/checkout@v2
      with:
        repository: ${{steps.get_data_repo.outputs.repo }}
        path: _data/machgen

    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-2.6.x-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-2.6.x-gems-

    - name: Cache pips
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.x-pip

    - uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.x

    - name: Install packages with pip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install lxml PyGithub pyyaml shapely pandas geopandas

    - name: Recreate CSV, JSON and GeoJSON and push them
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_REPO_NAME: covid19gr_issues
      working-directory:
        _data/machgen/
      run: |
        mkdir -m 700 ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        cat ~/.ssh/id_ed25519
        pushurl="git@github.com:$(git config --local remote.origin.url | sed 's;^https://github\.com/;;')"
        git config remote.origin.pushurl "$pushurl"
        git fetch origin
        git reset --hard origin/master
        ../../scripts/github2CSV.py issues.csv issuesjson.json issues.geojson ../../_utilities ${{ secrets.ACCEPTED_LABEL }}
        git config --local user.name "ehack-italy"
        git config --local user.email "62019251+ehack-italy@users.noreply.github.com"
        git commit -m "Aggiorno automaticamente dati $(date -Iseconds)" -- issues.csv issuesjson.json issues.geojson && git push || :
